[project]
name = "shioru-stats"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "ollama>=0.5.3",
    "polars>=1.33.0",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
]
